-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 20:19:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Porfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Porfile` (
  `id` VARCHAR(45) NOT NULL,
  `pushId` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `address` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL COMMENT '头像',
  `sex` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `profile` VARCHAR(45) NULL COMMENT '个人信息',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `key_profile_idx` (`profile` ASC) VISIBLE,
  CONSTRAINT `key_profile`
    FOREIGN KEY (`profile`)
    REFERENCES `mydb`.`Porfile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`firends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firends` (
  `id` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `orgin_id` VARCHAR(45) NOT NULL,
  `target_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `orgin_id_UNIQUE` (`orgin_id` ASC) VISIBLE,
  UNIQUE INDEX `target_id_UNIQUE` (`target_id` ASC) VISIBLE,
  INDEX `orgin_id_idx` (`orgin_id` ASC, `target_id` ASC) VISIBLE,
  CONSTRAINT `target_id`
    FOREIGN KEY (`orgin_id` , `target_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orgin_id`
    FOREIGN KEY (`orgin_id` , `target_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `bid` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `upper` VARCHAR(45) NULL COMMENT '上传者',
  `author` VARCHAR(45) NULL COMMENT '书籍的作者',
  `Bookscol` VARCHAR(45) NULL,
  PRIMARY KEY (`bid`),
  UNIQUE INDEX `gid_UNIQUE` (`bid` ASC) VISIBLE,
  INDEX `upper_idx` (`upper` ASC) VISIBLE,
  CONSTRAINT `upper`
    FOREIGN KEY (`upper`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goods` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `bId` VARCHAR(45) NULL COMMENT '通过商品信息，获取book的信息',
  `uId` VARCHAR(45) NULL COMMENT '用户的id，用户查询自己的商品信息',
  `count` INT NULL COMMENT '购买的数量',
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `bId_idx` (`bId` ASC) VISIBLE,
  INDEX `uId_idx` (`uId` ASC) VISIBLE,
  CONSTRAINT `bId`
    FOREIGN KEY (`bId`)
    REFERENCES `mydb`.`Books` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uId`
    FOREIGN KEY (`uId`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `mId` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `toUser` VARCHAR(45) NULL,
  `fromUser` VARCHAR(45) NULL,
  `msg` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL COMMENT '类别',
  `attach` VARCHAR(45) NULL COMMENT '附件',
  PRIMARY KEY (`mId`),
  UNIQUE INDEX `mId_UNIQUE` (`mId` ASC) VISIBLE,
  INDEX `to_User_idx` (`toUser` ASC) VISIBLE,
  INDEX `from_User_idx` (`fromUser` ASC) VISIBLE,
  CONSTRAINT `to_User`
    FOREIGN KEY (`toUser`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `from_User`
    FOREIGN KEY (`fromUser`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Micro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Micro` (
  `mID` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`mID`),
  UNIQUE INDEX `mID_UNIQUE` (`mID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `cId` VARCHAR(45) NOT NULL,
  `eId` VARCHAR(45) NOT NULL COMMENT '评论事件源',
  `uID` VARCHAR(45) NOT NULL COMMENT '评论者',
  `c_uID` VARCHAR(45) NOT NULL COMMENT '评论用户的Id',
  `update_time` TIMESTAMP NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cId`),
  UNIQUE INDEX `cId_UNIQUE` (`cId` ASC) VISIBLE,
  UNIQUE INDEX `eId_UNIQUE` (`eId` ASC) VISIBLE,
  UNIQUE INDEX `uID_UNIQUE` (`uID` ASC) VISIBLE,
  UNIQUE INDEX `key_eID_UNIQUE` (`c_uID` ASC) VISIBLE,
  CONSTRAINT `eId`
    FOREIGN KEY (`eId`)
    REFERENCES `mydb`.`Micro` (`mID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uID`
    FOREIGN KEY (`uID`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `key_id`
    FOREIGN KEY (`c_uID`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`live`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`live` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `lID` TIMESTAMP NOT NULL,
  `master` VARCHAR(45) NULL,
  `watcher` VARCHAR(45) NULL,
  PRIMARY KEY (`lID`),
  INDEX `master_idx` (`master` ASC, `watcher` ASC) VISIBLE,
  CONSTRAINT `master`
    FOREIGN KEY (`master` , `watcher`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
